title: Meu Blog 
description: Bem-vindo ao meu site!
author:
- Renata Roque
logo: /hcz-jekyll-blog/static/img/me.png
github: https://github.com/codeasashu
about: Mestranda em Estatística Aplicada e Biometria
baseurl: https://codeasashu.github.io/hcz-jekyll-blog
url: https://seusite.github.io
allowsearch: yes
disqus_shortname: aboutashu
google_analytics: UA-72862926-1
share:
  twitter_username: \#
  fb_appid: 0
enableTags: yes
tagarray: []
paginate: 20
per_page: 20
paginate_path: /page:num/
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-gist
